#Get health check
GET http://localhost:8080/api/v1/alive


#Get all books
###
GET http://localhost:8080/api/v1/livro/all

#Create book
###
POST http://localhost:8080/api/v1/livro/new
Content-Type: application/json

{
  "titulo": "O Livro do Desassossego",
  "autor": "Fernando Pessoa"
}

###
#Get book by id
GET http://localhost:8080/api/v1/livro/1

###
#Delete book by id
DELETE http://localhost:8080/api/v1/livro/12
###
#Find book by title and author
GET http://localhost:8080/api/v1/livro/find?titulo=Drácula&autor=Bram Stoker

###
#Create avaliacao
POST http://localhost:8080/api/v1/avaliacao/new
Content-Type: application/json

{
  "titulo": "Review 7",
  "autor": "Telmo",
  "review": "Meh book",
  "rating": 3,
  "votos": 0,
  "livro": {
    "id": 1
  }
}

###
#Get avaliacao by id
GET http://localhost:8080/api/v1/avaliacao/5

###
#Get all avaliacoes
GET http://localhost:8080/api/v1/avaliacao/all

###
#Get all avaliacoes by livro id
GET http://localhost:8080/api/v1/livro/1/avaliacoes/all

###
#Create new comentario
POST http://localhost:8080/api/v1/comentario/new
Content-Type: application/json

{
  "autor": "Bram Stoker",
  "mensagem": "Kinda based no?",
  "avaliacao": {
    "id": 3
  }
}

###
#Get avaliacao comentarios
GET http://localhost:8080/api/v1/avaliacao/3/comentarios/all